image: mcr.microsoft.com/dotnet/sdk:5.0

stages:
  - build
  - test

build_job:
  stage: build
  script:
    - dotnet restore
    - dotnet build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

test_job:
  stage: test
  script:
    - dotnet test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
